### ISSUE TITLE
Baustellenmodus

### ISSUE THREAD

**Issue by alexplusde** [RexDude/xcore#133]
Hi!

Noch eine Anregung/Idee: Bei der Installation neuer Seiten empfiehlt es sich ja, diese mit einer .htpasswd geschützt zu installieren - sofern man nicht lokal entwickelt. Irgendwie findet Google ja doch zu einem und dann landet eine halbfertige Seite auf dem Index (blöd). 

Gerade, weil SEO42 schon viel in der Richtung abwickelt, wäre eine pauschale 1-Click-Lösung doch ein nettes Feature, z.B. unterhalb der Checkbox "Directory Listenings", die eine htpasswd-Datei anlegt (z.B. admin/admin) und den Auth-Pfad in der htaccess-Datei automatisch anlegt und anpasst.

Ist sicher nicht oberste Priorität und wenn's nicht Teil von seo42 würde, wäre es auch zu verschmerzen. Aber ist mir gerade eingefallen.

**Comment by elricco** [comment]
Hi!
Darüber hab ich auch schon nachgedacht - und zwar als PlugIn. Und es dann folgendermaßen zu lösen: eine .htpasswd aus den Usernamen und PW von REDAXO generieren. Dann den Pfad ermitteln zu der Datei. Deine übliche .htaccess Datei sichern, übernehmen und oben nur den Eintrag zur .htpasswd hinzufügen.
Beim deaktivieren dann deine Datei wiederherstellen / drüberkopieren und die .htpasswd löschen.
Als optionale Einstellung könnte man noch festlegen lassen, wie die "Protected Area" heißen soll. Aber das ist ja nur Spielerei ;)

Vielen Dank für die Aufmerksamkeit.

**Comment by RexDude** [comment]
Ist für X-Core angedacht.
