### ISSUE TITLE
 Automatische Redirects funktionieren nicht bei per EP hinzugefügten URLs

### ISSUE THREAD

**Issue by TobiasKrais** [RexDude/xcore#148]
Beispiel: zuerst die korrekte URL http://www.kaltenbach.com/de/powerful-solutions/produkte/maschinen/bandsaegemaschinen/. Die URL des zugehörigen Artikels lautet http://www.kaltenbach.com/de/powerful-solutions/.

Entferne ich nun von der korrekten URL das letzte "/" (http://www.kaltenbach.com/de/powerful-solutions/produkte/maschinen/bandsaegemaschinen) wird auf den Artikel weitergeleitet, nicht auf die per EP hinzugefügte korrekte URL.

Grund: die Methode für die Weiterleitung nimmt keine URL Parameter entgegen. Lösung: Methode müsste optional einen Parameterarray entgegen nehmen, der per default leer ist.

**Comment by RexDude** [comment]
seo42 ist ja geschichte. falls x-core noch mehr redirect mechanismen beherrschen sollte wird das berücksichtigt.
