### ISSUE TITLE
"Alle aufklappen" bei den Einstellungen

### ISSUE THREAD

**Issue by olien** [RexDude/xcore#193]
Nur ein bescheidener Wunsch...

![auf_zu](https://cloud.githubusercontent.com/assets/330516/10878478/1e11e598-814e-11e5-85e9-f248728940d8.png)

**Comment by RexDude** [comment]
Hmm, wollt die Einstellungsseite eh noch verbessern, damit auch die geöffneten Sections nach speichern der Settings weiterhin offen bleiben.

**Comment by RexDude** [comment]
tabs sind für X-Core angedacht wenn einstellungen zu viele werden sollten.
