### ISSUE TITLE
Seite "Einstellungen" verbessern

### ISSUE THREAD

**Issue by alexplusde** [RexDude/xcore#195]
Ich habe mal versucht, die einzelnen Einstellungen auf der Einstellungsseite treffender zu formulieren und jeder Funktion einen kurzen, erklärenden Beschreibungstext hinzuzufügen.

https://docs.google.com/spreadsheets/d/1TJpEsZnDw4TS6X4XONhpn1cSfJOYCkLGBCH3dOsmx3U/edit?usp=sharing

Bei ein paar Funktionen bin ich mir jedoch selbst unsicher, was sie machen, weil ich den 2. Teil von deiner Session am Samstag nicht mitbekommen habe.

Aber falls dir meine Änderungsvorschläge von den Bezeichnungen im Großen und Ganzen zusagen, würde ich das gerne für dich weiter ausbauen.

**Comment by RexDude** [comment]
Coooool :dancer: 
Das nimmt mir jede Menge arbeit ab.
Kommt in die nächste Version mit rein.
Danke!

**Comment by alexplusde** [comment]
Dann werde ich da an einer handvoll Stellen noch mal ein paar Sachen ändern und die Lücken beheben.

**Comment by RexDude** [comment]
Ok mach das.
Ich geh da erst durch wenn ichs einbauen werd :)

**Comment by polarpixel** [comment]
Super, Alex! Sowas habe ich seit Ewigkeiten vor, aber eben auch noch nicht angefangen. Wenn Ihr wollt, kann ich mit an den Formulierungen feilen (hatte ja im Studium solche Sachen wie Textredaktion, technische Dokumentation, etc.). So würde ich z.B. vorschlagen, dass wir zu vermeiden versuchen, immer mit "Gibt an ... " anzufangen.
Also z.B. statt:
_Gibt an, ob URLs, die mit oder ohne fehlendes "/" oder ".html" auf den richtigen Artikel umleiten sollen._
lieber:
_URLs mit oder ohne fehlendes "/" oder ".html" werden auf den korrekten Artikel umgeleitet._

Rudi hatte mir mal alle Optionen erklärt, aber ich weiß sie auch nicht mehr. Evtl. können wir ja einen Skype-Chat oder -Telefonat zu dritt machen, wo wir die noch unklaren Sachen durchgehen.

(@alexplus Der zweite Teil von SEO42 fiel leider aus, Du hast ihn also nicht verpasst ...)

**Comment by alexplusde** [comment]
@polarpixel gerne! Ich hatte auch verschiedene Kurse rund um Textdesign / Technische Dokumentation belegt und war daher mit der Formulierung auch noch nicht zufrieden. Aber: Erst, wenn was da steht, kann man es auch verbessern. Bin da total offen. :) 

Den Skype-Chat hatte ich auch im Sinn. Dann passt's ja!

**Comment by polarpixel** [comment]
Völlig richtig! Deswegen ist Deine Vorleistung natürlich absolut genial!

@RexDude, gibst Du uns mal bei Gelegenheit per Skype eine Erklärung?

**Comment by RexDude** [comment]
Machen wirs so: ich versuche das ganze so gut es geht direkt zu übernehmen. Fehlende Einträge werd ich schauen dass ich diese ergänze. Und ihr schaut dann nochmal final drüber ;)

**Comment by alexplusde** [comment]
Hi Rudi,

Peter hat sich leider vorerst ausgeklinkt wegen der R5-Doku. Ich habe noch ein paar Stellen korrigiert. 

Bei einigen Einstellungen müsstest du mir kurz helfen, was sie in etwa bezwecken bzw. einen Text vorformulieren. (Gekennzeichnet mit "??"). Gib einfach Bescheid, wenn ich was machen soll.

**Comment by RexDude** [comment]
Ich danke dir lieber Alex. Da du so engagiert bist könntest du jetzt in einem nächsten Schritt eine SETTINGS.MD erstellen basierend auf deinem Doc. Struktur der md kannst du hier abschauen: https://github.com/RexDude/seo42/commit/7b810d7adab1ce59a19ed5af8718b0456b2509bb
Vorgeschlagene Namensänderungen kannst du in Klammer dazu schreiben bei den Überschriften.
Wo was fehlt oder ergänz werden muss ein <TODO> dazu.
Das ganze dann als Pull Request oder einfach hier rein droppen.
Alles verstanden? :)

**Comment by alexplusde** [comment]
Gerade nach dem PR noch mal das Issue gesehen. Das mit den vorgeschlagenen Namensänderungen habe ich noch nicht in Klammern dazu geschrieben. Betrifft aber fast alle, weil ich auch so Kleinigkeiten wie nen fehlenden Bindestrich ergänzt habe. Hatte kein Internet im Zug. Ich denke, ich überarbeite das noch mal.

**Comment by RexDude** [comment]
Ok :)

**Comment by alexplusde** [comment]
ist wohl doch eher +3 Tage geworden, sorry. Privat war viel los, aber jetzt habe ich's noch mal aufbereitet. An ein paar Stellen wäre es nett, wenn du meine Lücken noch ergänzt. Ich hoffe, es ist dir (und der Community) eine Hilfe :)

Fröhliche Feiertage!

**Comment by RexDude** [comment]
Danke und kein Problem. Und wo ist jetzt das fertige MD File? ;)

**Comment by alexplusde** [comment]
Das hing fest, du müsstest den PR gerade bekommen haben. Zug und Internet vertragen sich nicht so ;)

**Comment by RexDude** [comment]
Ja danke. PR ist da :)
Schönes Weihnachtsgeschenk :)
Mal gucken ob ich dir dafür auch mal einen Muffin backen kann ;)

**Comment by RexDude** [comment]
Ist für X-Core angedacht.

**Comment by alexplusde** [comment]
Der Muffin oder die Erläuterungen? ;)

Schön, dass du wieder mit am Start bist. 

Hast du einen Überblick, welche Funktionalitäten bereits von Haus aus / in YRewrite / in URL umgesetzt sind? Wäre schade, wenn es wieder so viele Dopplungen von Addons wie in R4 und manchmal auch in R5 gibt.

**Comment by RexDude** [comment]
;)

Aktuell wird yRewrite zu 100% als Rewriter verwendet und nur ein Schema mitgeliefert um z.B. .html einstellen zu können als Url Endung.
Was die Zukunft bringt weiss ich aber nicht. Möglich ist dass X-Core dass Rewriting und  noch mehr wieder übernimmt (wie SEO42 ;)).
