### ISSUE TITLE
Umlaut-Domain führt zu Endlos-Weiterleitung

### ISSUE THREAD

**Issue by alexplusde** [RexDude/xcore#215]
Gerade getestet: Wenn man als "URL der Website" eine Umlaut-Domain uncodiert einträgt, z. B. www.häppy.de, schießt sich die Website ab. Codiert eintragen hilft: 
www.xn--hppy-loa.de

Lösungsansatz: URL mit http://php.net/manual/de/function.idn-to-ascii.php behandeln.

Alternativ:
Dokumentieren, wie Umlaut-Domains eingetragen werden müssen.

**Comment by RexDude** [comment]
Sowohl extra Ports in Url als auch Umlaut Domains sind noch nicht berücksichtigt.
Muss man aber wohl machen ;)

**Comment by RexDude** [comment]
Ist für X-Core angedacht (wenn so die alte seo42 Funktionalität wieder reinfinden sollt).
