### ISSUE TITLE
Nicht vollständig PHP 7 kompatibel

### ISSUE THREAD

**Issue by Hirbod** [RexDude/xcore#221]
Wenn ich das AddOn mit PHP 7 auf einer mehrsprachigen Seite nutze, funktioniert nichts mehr. Die Startseiten der Sprachen sind falsch, die PATHLIST wird fehlerhaft generiert.

Ich hab wirklich nen ganzen Tag versucht zu debuggen, ich bekomm es nicht zum Laufen.
Es wäre super, wenn du das PHP 7 Thema noch mal testen könntest und ggf. alles fixed.

Falls notwendig, gebe ich dir gerne Zugriff auf ein Testsystem. Das ganze läuft auf REX 4.7.1 mit dem MySQL Shim. Nicht mehrsprachige Seiten konnte ich problemlos updaten, da lief es mit SEO42 einwandfrei.

**Comment by RexDude** [comment]
Ok ich schau mal danach. Wenn ich Zugang brauch meld ich mich.

**Comment by RexDude** [comment]
Hab dir noch ne Mail geschickt...

**Comment by RexDude** [comment]
Also ich werde wenn die 4.7.2 raus ist seo42 auch nochmal mit sprachen testen.

**Comment by Hirbod** [comment]
Für mich hat sich das Thema erledigt. Ich hab besagte Webseite nach REX5 portiert.

**Comment by RexDude** [comment]
Ok passt.
