### ISSUE TITLE
multiupload

### ISSUE THREAD

**Issue by Hirbod** [RexDude/xcore#222]
Kannst du bitte https://github.com/RexDude/xcore/blob/master/boot.php#L40-L57 wieder entfernen? Das war nur ein Test und wird später von mir behoben und über eine Settings-Page gesteuert. Dein AddOn würde das jetzt pauschal immer wieder einschalten.

Ich release das morgen.

**Comment by RexDude** [comment]
hey, ich habe auch einstellungen noch geplannt für das ganze zeugs. wenn in multupload ne einstellung reinkommt dann kann ich dass aber gerne auch ganz entfernen.

**Comment by RexDude** [comment]
Eine Einstellung ist drin. Wenn du bei dir die Einstellung setzt gib mir bescheid, dann nehm ich den Code ganz raus.

**Comment by RexDude** [comment]
@Hirbod Die Pages sind normal wieder da (wie früher) oder?

**Comment by Hirbod** [comment]
Ja, ganz normal da. Ich baue im nächsten Update ne Settingspage. Ich pushe gleich das Update in den Installer. Wenn du gerade dabei bist, kannst du gern das neue Plugin ImageOptimizer testen :)

**Comment by RexDude** [comment]
ok cool :) 
imageoptimizer...ist das der nachfolger vom precompressor? ;)

**Comment by Hirbod** [comment]
Nein, ein Zusatzplugin.

**Comment by RexDude** [comment]
ok musst dann mal die readme überarbeiten  noch :)

**Comment by Hirbod** [comment]
kommt in 25 sekunden :)

**Comment by RexDude** [comment]
Fix wie immer :)

**Comment by Hirbod** [comment]
Hehe, danke. Habs eben noch mal editiert, um auf den Upload + Media Manager Effekt hinzuweisen.

**Comment by RexDude** [comment]
Sauber Hirbod. Doku schreiben find ich immer am aufwändigsten (wenn mans mal schafft :D)
