### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Hirbod** [RexDude/xcore#223]
Hi,

würde gern mit deiner Erlaubnis den Header-Fix in mein Addon media_manager_autorewrite mit reinpacken. Ist das ok für dich?

**Comment by RexDude** [comment]
Ja aber na klar. Du kannst alles nehmen was Opene Source von mir ost und machen was du willst damit :)

**Comment by RexDude** [comment]
Danke fürs nachfragen trotzdem :)

**Comment by Hirbod** [comment]
Gilt auch für mein Zeug

**Comment by RexDude** [comment]
Danke!
