### ISSUE TITLE
X-Chat

### ISSUE THREAD

**Issue by marcohanke** [RexDude/xcore#224]
Hey Rexdude, kennst du eigentlich den FriendsOfRedaxo Slack Channel? http://www.redaxo.org/slack/ Ich denke du und deine Addons sind da sehr willkommen ;-)!

**Comment by RexDude** [comment]
Hey Marco, danke fürs mitdenken. Ja kenn ich natürlich. Chatten kann man jetzt auch hier bis auf weiteres im neuen X-Chat :))

**Comment by marcohanke** [comment]
Hey Dude, geht klar. Falls du irgendwann Lust auf FOR verspürst, wäre das trotzdem cool ;-)

**Comment by RexDude** [comment]
Gut weiss ich bescheid ;)

**Comment by RexDude** [comment]
Tja mein Plan ist wohl nicht aufgegangen mit dem X-Chat. Bitte Issues nur für Bug oder Feature Meldungen benutzen. DANKE!
