### ISSUE TITLE
404 bei Startartikel

### ISSUE THREAD

**Issue by Hirbod** [RexDude/xcore#225]
Redaxo sendet bewusst keinen 404, wenn Startartikel = Fehlerartikel ist. Wir hatten das in der Vergangenheit in REX 3 oder REX 4 mal aktiv. Google hat diverse Startseiten aus dem Index deswegen geschmissen. Solltest du nicht aktivieren, außer du hast ein Dokument darüber, dass Google da nicht mehr abwertet.

**Comment by RexDude** [comment]
Hmm zur Sicherheit könnte man dann einfach den Startseiten Content net anzeigen. Keinen 404 zu senden geht gar nicht.

**Comment by Hirbod** [comment]
Wenn der Enduser keinen expliziten Fehlerartikel auswählt, solltest du da nichts machen..

**Comment by RexDude** [comment]
Ich bau ein 404 Template ein: https://w3layouts.com/preview/?l=/funky-404-free-web-and-mobile-website-template/ 
Typo3 macht dass ja auch ;)
