### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexplusde** [RexDude/xcore#226]
Hi Rudi,

ich hab's offiziell noch nirgends geschrieben, aber ich find's klasse, wieder von dir zu hören. Da du nicht in Slack bist (und ich nicht mehr ins Forum schaue), aber die Frage sicherlich von öffentlicher Relevanz ist:

Wie schaut es aus mit einer Roadmap? 
Welche Pläne werden mit xcore weiter verfolgt? 
In wie weit planst du, Feature-Wünsche zu berücksichtigen?
Kann man dich in der Arbeit irgendwie unterstützen?

Ich bspw. schwanke, ob ich wieder zu deinen Addons zurück wechsle oder bei den FOR-Addons bleibe. 

Bis heute sind Features einiger Addons dort nicht oder nicht so (an meinem Workflow gemessen) komfortabel umgesetzt wie in xcore, auf der anderen Seite würde ich gerne langfristig mit den gewählten Addons arbeiten - da hat die FOR-Gemeinschaft natürlich das Versprechen, dass die Addons nicht im Nirvana zu verschwinden, wenn einzelne Entwickler gehen.

Vielleicht kannst du dazu kurz deine Position formulieren?

Liebe Grüße

**Comment by RexDude** [comment]
schäzelein ich will nicht unhöfflich sein aber mich stress dieses issue. schon wieder gehts um for und um zukunft und um sicherheit etc. bitte bitte lasst mich doch einfach meine sachen machen so wie ich sie für richtig halte. gefällt es euch benutzt es gerne. gefällt es euch nicht nehmt was anderes oder forkt es euch und macht was ihr wollt damit. ne sicherheit kann ich bei meinen Open Source ENtwicklungen keinem geben. 
@alexplusde wir können gerne mal telefonieren und uns austauschen wenn du noch bedarf hast. und meine email hast du auch! aber alles andere kostet mich jetzt nur unnötig zeit. zeit in die ich bereits in ein neues feature stecken könnte ;) deshalb close und lock. Liebe Grüße!
P.s: Bugmeldungen sind immer willkommen und werden versucht zeitnah zu bearbeiten (aber ohne Garantie!) Featurewünsche gehn auch immer, die werden aber erstmal gesammelt da ich wie gesagt genug Ideen habe und ich selber schauen muss wohin ich dass Addon steuern werde (oder ob überhaupt :P)
