### ISSUE TITLE
CSS-Tweaks im Backend: Images auf max-width: 100%

### ISSUE THREAD

**Issue by alexplusde** [RexDude/xcore#227]
Könntest du noch mit aufnehmen. Sonst hat man in Modulen und Addons von Haus aus sowas hier:

![image](https://cloud.githubusercontent.com/assets/3855487/24368171/c2af2a48-131f-11e7-8e3b-3660e684e54c.png)

Wurde im Core leider abgelehnt.
https://github.com/redaxo/redaxo/issues/739

**Comment by RexDude** [comment]
In den Blöcken ist dass schon drin :)

**Comment by skerbis** [comment]
Ist nun in REDAXO:
https://github.com/redaxo/redaxo/pull/1181

**Comment by alexplusde** [comment]
Dann mach ich's mal zu hier.
