### ISSUE TITLE
CSS-Tweaks im Backend: leere Tabellen

### ISSUE THREAD

**Issue by alexplusde** [RexDude/xcore#228]
![image](https://cloud.githubusercontent.com/assets/3855487/24368311/3a7cdc78-1320-11e7-940a-00d6cfc5a6d6.png)

Bei leeren Tabellen-Zeilen nur mit Kopfzeile wird die unterste Linie nicht gezeichnet.

**Comment by RexDude** [comment]
Ist das noch relevant für dich? Wenn ja schick doch ein PR oder Codeschnipsel. Ich kann sonst mit der fehlenden Linie leben ;)

**Comment by alexplusde** [comment]
Hey @RexDude, ich hab xcore nicht mehr im Einsatz. Irgendwie schade, aber vieles wurde seither nachgerüstet. (bis auf die Tatsache, das grün zu entfernen ;))

LG

**Comment by RexDude** [comment]
Hab verstanden ;)
