### ISSUE TITLE
@import in der SCSS-Datei funktioniert nicht

### ISSUE THREAD

**Issue by bega011** [RexDude/xcore#229]
Noch ein Wunsch für XCore :)
wie bei Seo42 #202

**Comment by RexDude** [comment]
Hast du es scho mit der dev version hier von github probiert?

**Comment by bega011** [comment]
Nur mit der aktuellen Version über Installer. Dann probiere ich es noch mit der Dev-Version ;)

**Comment by bega011** [comment]
Hmm, klappt nicht. Dieselbe Story wie letzte Woche mit Websitemanager in R4 :(

**Comment by RexDude** [comment]
schick mir mal dein scss package damit ich was zum testen hab.

**Comment by RexDude** [comment]
Und ne Fehlermeldung brauch ich auch ;)
