### ISSUE TITLE
Fehler in rexx::isSliceOfSameType nach Kopieren der Slices von Liveversion in Arbeitsversion

### ISSUE THREAD

**Issue by helpy** [RexDude/xcore#230]
Ich habe die aktuellsten Versionen:
- Redaxo 5.5.0
- xcore 1.1.1
- version 2.5.0

Ich habe folgendes gemacht:
- Arbeitsversion war leer
- Liveversion hatte 2 Slices in ctype 1
- Liveversion hatte 3 Slices in ctype 2
- Auf Liveversion umgeschaltet und Inhalte von Arbeitsversion kopiert.
- Auf Arbeitsversion umgeschaltet

Nun kam die Fehlermeldung, dass in der Funktion rexx::isSliceOfSameType beim Aufruf von $slice = $curSlice->getPreviousSlice(); in Zeile 1181 $slice den Wet null hat!

Ich habe dann den Code geändert von:
```php
    if ($previous) {
      $slice = $curSlice->getPreviousSlice();
    } else {
      $slice = $curSlice->getNextSlice();
    }
```

in:
```php
    if ($previous) {
      if (rexx::isSliceValid($curSlice))
        $slice = $curSlice->getPreviousSlice();
    } else {
      if (rexx::isSliceValid($curSlice))
        $slice = $curSlice->getNextSlice();
    }
```

Danach konnte ich im Backend wieder umschalten auf die Arbeitsversion.

Ob das gutes Coding ist, weiß ich nicht, da ich die Zusammenhänge in diesem AddOn nicht kenne.
Das war für mich nur ein schneller Bugfix, der funktioniert hat.

Viele Grüße,
Guido

**Comment by RexDude** [comment]
Hi und danke dir für den ausführlichen Bericht :)
Die isSliceValid Prüfung würde ich dann einfach ausweiten, sie ist weiter unten ja schon da. 
Leider verstehe ich nicht genau  warum hier curSlice null ist und die Frage ist auch was die Methode dann zurückgeben sollt wenn dass passiert.

**Comment by helpy** [comment]
Gibt es irgendetwas, was ich tun kann, um das Problem einzugrenzen und die Ursache zu lokalisieren?

**Comment by RexDude** [comment]
Danke sehr nett. Ich versuche zuerstmal den Fehler zu reproduzieren anhand deiner Beschreibung und gebe dann wieder bescheid.

**Comment by helpy** [comment]
Ich habe nochmal nachgesehen welche rexx::* Funktionen ich in den Modulen verwendet habe.

In Spalte ctype=1:
- rexx::isBackend()

In Spalte ctype=2:
- rexx::getArticle()
- rexx::getSliceStatus()
- rexx::isFirstSliceOfSameType()
- rexx::isLastSliceOfSameType()
- rexx::isBackend()
- rexx::isFrontend()

Eine dieser Funktionen ruft dann wohl rexx::isSliceOfSameType() auf. Wahrscheinlich die beiden:
- rexx::isFirstSliceOfSameType()
- rexx::isLastSliceOfSameType()

**Comment by RexDude** [comment]
Ja genau.

**Comment by RexDude** [comment]
Also ich konnts leider nicht wirklich reproduzieren. Aber die Exception sollte jedefalls schon mal nicht mehr kommen.

**Comment by helpy** [comment]
Getestet auf meinem System: Fehler behoben!
