### ISSUE TITLE
getImageManagerFile 

### ISSUE THREAD

**Issue by webregie** [RexDude/xcore#232]
Hellö!
In SEO42 gab es diese schöne Funktion um auf verkleinerte Bilder aus dem Image Manager zuzugreifen. Ich habe leider nichts ähnliches hier gefunden. Geplant? Rausgeworfen?

seo42::getImageManagerFile("file.gif", 'Typ')

**Comment by skerbis** [comment]
Suchst du das? 
@webregie 

`$media = rex_media_manager::create($type, $file)->getMedia();
$media->getFormat();
$media->getWidth();
$media->getHeight();`

**Comment by webregie** [comment]
Nein, ich suchte 

rexx::getManagedMediaFile(string $mediaFile, string $mediaType, bool $validHtml=true) : string

Habe es somit gefunden. 

Sorry!

**Comment by RexDude** [comment]
Yo stimmt, ist sogar in der Readme ;)
