### ISSUE TITLE
Speichern der Config in REDAXO 5.6 nicht möglich

### ISSUE THREAD

**Issue by pschuchmann** [RexDude/xcore#237]
Nach Update auf REDAXO 5.6 ist es nicht mehr möglich die Config zu speichern.
Gibt es dazu einen schnellen fix?

**Comment by RexDude** [comment]
Kommt eine Fehlermeldung? Steht was im System Log?

**Comment by fietstouring** [comment]
kann ich bestätigen. Es kommt die Meldung "Einstellung gespeichert", die Settings gehen aber wieder in der Zustand davor zurück.

**Comment by fietstouring** [comment]
Systemlog ist leer

**Comment by RexDude** [comment]
@gharlan Ich habe gesehen ihr habt an der rex_config Klasse geschraubt. Irgend eine Idee?

**Comment by gharlan** [comment]
Ich hab mir das angeschaut.
Letztlich Auslöser ist diese Änderung: https://github.com/redaxo/redaxo/pull/1624

Der Ablauf ist so:
- XCore setzt die neue Config (setConfig), rex_config speichert aber immer erst ganz am Ende des Requests, die Werte sind also erst mal nur gesetzt in der rex_config Klasse (da hat sich nichts geändert)
- XCore [löscht den YRewrite-Cache](https://github.com/RexDude/xcore/blob/master/pages/config.php#L24)
- YRewrite [löscht da aber den Gesamt-Cache](https://github.com/yakamara/redaxo_yrewrite/blob/master/lib/yrewrite.php#L624-L627)
- Der Core [refresht rex_config](https://github.com/redaxo/redaxo/blob/master/redaxo/src/core/functions/function_rex_other.php#L29) dabei aber seit 5.6
- Dadurch werden die Werte neu aus der DB geholt, und die vorher per setConfig gesetzten sind weg

Blöde Sache. Muss ich mal drüber nachdenken, wie man das löst.
Die Frage ist zum Beispiel, ob yrewrite denn wirklich den Gesamt-Cache löschen muss. Eventuell könnte man das Problem (vorerst) in yrewrite lösen.

/cc @staabm

**Comment by RexDude** [comment]
@gharlan Top Auswertung! :)

Könnte man nicht ein flushen (also sofort in DB speichern) der rex_config Werte erzwingen direkt nach dem setConfig aufruft, z.B. durch einen weiteren Methoden aufruf (direkt nach setConfig). Oder setConfig direkt zum Speichern bringen. Oder setConfig per extra bool Parameter zum direkten Speichern bringen.

**Comment by RexDude** [comment]
Oder ich lösch hier im Addon den Cache am Ende irgendwann per EP (Output Filter?) als Workaround.

**Comment by gharlan** [comment]
Du kannst `rex_config::save()` aufrufen, damit könntest du es wahrscheinlich selbst erst mal lösen.

**Comment by RexDude** [comment]
Ok Danke. Ich habe mal das save() eingebaut. Kann dass jemand testen? @fietstouring @pschuchmann

**Comment by fietstouring** [comment]
yupp, funktioniert. Einstellung wird auch wirklich übernommen (habs mit dem Title-Tag Trenner getestet)

**Comment by RexDude** [comment]
Super danke dir und euch.

**Comment by pschuchmann** [comment]
War Freitag im Urlaub und konnte nicht testen, danke für den schnellen Fix!

**Comment by TobiasKrais** [comment]
Könnte man den in die `rex_delete_cache()` Methode nicht den `rex_config::save()` einbauen.
