### ISSUE TITLE
Kontrolle auf bereits vorhandene umgeschriebene URL

### ISSUE THREAD

**Issue by SigmaAlphaPi** [RexDude/xcore#66]
Hi,

Bisher scheint SEO42 nicht zu testen (was Du ja schon bestätigt hast), ob eine URL bereits benutzt wird. Wenn zufällig zwei Artikel gleich benannt werden, führt dies dazu, dass der zweite Artikel im FE nicht angesprochen werden kann.

VG,
Sven

**Comment by RexDude** [comment]
Ist für X-Core geplannt.
