### ISSUE TITLE
Multidomain Modus

### ISSUE THREAD

**Issue by RexDude** [RexDude/xcore#72]
domain.com --> clang = 0 
domain.de --> clang = 1
domain.es --> clang = 2

Erster Test der schon grob funzt:
https://github.com/RexDude/seo42/tree/multidomain2

**Comment by omphteliba** [comment]
Also nur um sich zu gehen : die erste Idee von @NGWNGW ist nicht umsetzbar?

Getrennte Domains mit eignen Seiten-URLs?

**Comment by RexDude** [comment]
Bei der aktuellen Architektur des Rewriters: nein, denke nicht.

**Comment by omphteliba** [comment]
Danke für die Info, Rudi :)

**Comment by RexDude** [comment]
Ist für X-Core angedacht.
