### ISSUE TITLE
Sitemaps.xml bei mehreren Sprachen

### ISSUE THREAD

**Issue by NGWNGW** [RexDude/xcore#98]
Hier eine Idee zur Sitemaps-Generierung bei mehreren Sprachen:

Nutzen von  rel="alternate" hreflang="x" 
Siehe: https://support.google.com/webmasters/answer/2620865?hl=en

Bisher wird ja jeder Artikel für die Sprachen per separaten URL Eintrag hinterlegt und enthält keine Information zur Sprache.

Was meinst du dazu?

**Comment by RexDude** [comment]
Ist für X-Core angedacht.
